camera_simulator:
    ros__parameters:
        path: "/home/andreas/Code/petra_ws/probot_single_images/K4.13_realsense"
        calibration_file: "/home/andreas/Code/test_ws/src/ros2_video_streamer/config/camera.yaml"
        type: "image"
        start: 0
        frame_id: "camera"
        camera_name: "narrow_stereo"
        image_topic: "/image"
        camera_info_topic: "/camera_info"
