camera_simulator:
    ros__parameters:
        path: "/media/psf/Home/Downloads/japan_camera.mp4"
        calibration_file: "/home/tatsuyai/ros2_ws/src/ros2_video_streamer/config/camera.yaml"
        type: "video"
        loop: "true"
        start: 0
        frame_id: "camera"
        camera_name: "narrow_stereo"
        image_topic: "/color/image_raw"
        compressed_image_topic: "/color/image_raw/compressed"
        camera_info_topic: "/color/camera_info"
